fix: Bump git versions used in Linux and Windows toolchain images
On a fresh `gclient sync`, `depot_tools` now runs `git checkout` with an
`--end-of-options` flag, which is not supported by the older versions of
git used in our Linux and Windows CI jobs.

This incompatibility results in cascading errors about the crashpad
checkout, stemming from:

```
error: pathspec '--end-of-options' did not match any file(s) known to git
```

This commit updates the installed `git` client in these images to ensure
that they can handle the arguments passed to them by `gclient`.

Windows installed MinGit; it's now updated from `2.26.2` to `2.55.0`,
the latest release.

Linux previously installed the latest version available in Ubuntu
repositories; it now uses `git-core/ppa` so it can install the latest
available version.